from socket import socket, AF_INET, SOCK_DGRAM, SOL_SOCKET, SO_BROADCAST, SO_REUSEADDR

SERVER_BIND_ADDRESS = ('', 67)
SERVER_BROADCAST_ADDR = ('<broadcast>', 68)
CLIENT_SOURCE_ADDR = ("", 68)
CLIENT_DESTINATIN_ADDR = ('<broadcast>', 67)

CLIENT_SOCKET = socket(AF_INET, SOCK_DGRAM)
CLIENT_SOCKET.setsockopt(SOL_SOCKET, SO_BROADCAST, 1)
CLIENT_SOCKET.setsockopt(SOL_SOCKET, SO_REUSEADDR, 1)
CLIENT_SOCKET.bind(CLIENT_SOURCE_ADDR)

SERVER_SOCKET = socket(AF_INET, SOCK_DGRAM)
SERVER_SOCKET.setsockopt(SOL_SOCKET, SO_BROADCAST, 1)
SERVER_SOCKET.setsockopt(SOL_SOCKET, SO_REUSEADDR, 1)
SERVER_SOCKET.bind(SERVER_BIND_ADDRESS)
